server:
  port: 8084
  name: prodPanel
#产线参数
prodProp:
  knifeDefaultLife: 5000
  plannedProduction: 800
spring:
  datasource:
      druid:
          db1:
              url: jdbc:sqlserver://localhost:1433;DatabaseName=seerbigdata
              username: sa
              password : root
          db2:
              url: jdbc:mysql://localhost:3306/demo
              username: root
              password: root
#          db3:
#              url: jdbc:oracle:thin:@192.168.136.222:ORCL
#              username: sa
#              password: sa123456
info:
  service-info: production panel service
  api-doc: /swagger-ui.html
swagger:
  basePath: com.seer.panel
  title: 车间生产线看板的API信息
  description: API信息有疑问请联系相关开发人员
  contact: ligw
  version: @project.version@
