spring:
    profiles:
        active: test
    aop:
        proxy-target-class: true
        auto: true
    datasource:
        druid:
            db1:
                driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
                filters: stat
                maxActive: 20
                initialSize: 1
                maxWait: 60000
                minIdle: 1
                maxIdle: 8
                timeBetweenEvictionRunsMillis: 60000
                minEvictableIdleTimeMillis: 300000
                validationQuery: select 'x'
                testWhileIdle: true
                testOnBorrow: false
                testOnReturn: false
                poolPreparedStatements: true
                maxOpenPreparedStatements: 20
                removeAbandoned : false
                maxPoolPreparedStatementPerConnectionSize : 50
            db2:
                driver-class-name: oracle.jdbc.OracleDriver
                initialSize: 5
                minIdle: 5
                maxActive: 20
mybatis-plus:
    # 如果是放在src/main/java目录下 classpath:/com/yourpackage/*/mapper/*Mapper.xml
    # 如果是放在resource目录 classpath*:mapper/*Mapper.xml
    mapper-locations: classpath*:mapper/**/*Mapper.xml
    configuration:
        #配置返回数据库(column下划线命名&&返回java实体是驼峰命名)，自动匹配无需as（没开启这个，SQL需要写as： select user_id as userId）
        map-underscore-to-camel-case: true
        cache-enabled: false
        #配置JdbcTypeForNull, oracle数据库必须配置
        jdbc-type-for-null: 'null'
logging:
    path:'D:\log'
