spring:
    profiles:
        active: dev
    datasource:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        maxIdle: 8
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
        removeAbandoned : false
        maxPoolPreparedStatementPerConnectionSize : 50
#        dialect: MYSQL
mybatis:
  mapper-locations: classpath*:mapper/*Mapper.xml
  #config-location: /mybatis-config.xml
  #type-aliases-package: com.seer.*.bean
#custom:
#  rest:
#    connection:
#      connection-request-timeout: 3000
#      connect-timeout: 3000
#      read-timeout: 3000
